name: advanced-workflow

on:
  push:
    branches:
      - master # או main, תלוי בשם הענף הראשי שלך
  pull_request:

jobs:
  pr_job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This runs only on Pull Requests!"

  master_push_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This runs only when pushing to master!"